project_name: sub2clash
builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - windows
          - linux
          - darwin
      goarch:
          - amd64
          - arm64
          - arm
          - "386"
      ldflags:
          - -s -w -X sub2clash/config.Version={{ .Version }}
      flags:
          - -trimpath
archives:
    - format: tar.gz
      format_overrides:
          - format: zip
            goos: windows
      wrap_in_directory: true
      files:
          - LICENSE
          - README.md
          - templates
