when:
  event: tag

steps:
  - name: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: nite07/sub2clash
      tag: ${CI_COMMIT_TAG}
      username: nite07
      password:
        from_secret: docker_password
