when:
  - event: cron
    cron: docker-nightly

steps:
  - name: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64,linux/arm/v7
      repo: nite07/sub2clash
      tag: nightly
      username: nite07
      password:
        from_secret: docker_password
